--liquibase formatted sql

--changeset alexenon2002:001-baseline dbms:postgresql logicalFilePath:db/changelog/changes/001-baseline.sql


CREATE TABLE public.members
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(255)                   NOT NULL,
    middle_name VARCHAR(255),
    surname     VARCHAR(255)                   NOT NULL,
    created_at  TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    deleted_at  TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE TABLE public.qr_codes
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code      UUID   NOT NULL,
    member_id BIGINT NOT NULL,
    CONSTRAINT ukjbhqni35qt5q7o9oab1wwww34 UNIQUE (code),
    CONSTRAINT fkir64uxido1gsaxbuqtdruc3mt
        FOREIGN KEY (member_id) REFERENCES public.members (id)
);